// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/kubeman/app/config"
)

// Injectors from wire.go:

func InitializeApplication(config2 config.Config) (application, error) {
	terraform := provideTerraform(config2)
	kubernetes := provideKubernetes(config2)
	kubeman := provideKubeman(terraform, kubernetes, config2)
	mainApplication := newApplication(terraform, kubernetes, kubeman)
	return mainApplication, nil
}
